[Tizen 6.0] Enable build with updated glibc
Since glibc 2.27 this header is required.

file-user.cpp:60:12: error: 'major' was not declared in this scope
   60 |   devMaj = major(dev);
      |            ^~~~~

Change-Id: I11a8b84c94ea20fef2060df2681f80407730c2bb
Signed-off-by: Mikhail Kashkarov <m.kashkarov@partner.samsung.com>
Signed-off-by: Sangwan Kwon <sangwan.kwon@samsung.com>